name: nav_frame
description: "navigation app for frames"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  logging: ^1.3.0
  simple_frame_app: ^7.0.0
  frame_msg: ^2.0.0
  intl: ^0.17.0 # Or the latest version
  async: ^2.11.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image: ^4.5.2
  http: ^1.2.1 # For making HTTP requests
  flutter_dotenv: ^5.1.0 # For environment variables
  geolocator: ^11.0.0 # For location services
  mapbox_maps_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - packages/frame_msg/lua/camera.min.lua
    - packages/frame_msg/lua/sprite.min.lua
    - packages/frame_msg/lua/imu.min.lua
    - assets/frame_app.lua
    - .env # Add .env file to assets
    - assets/
